### ISSUE TITLE
Error "Not enough storage space to install required resources".

### ISSUE THREAD

**Issue by alexsaenko27** [Oleur/android-unity-as-library-sample#1]
Hello Julien,

I'm trying out your amazing sample application, but I'm also having some troubles.
In particular, when I launch the Unity player by clicking the "Start" button, I get this kind of error. However, I'm pretty sure my device has a lot of space available.

Do you know what could be due to a problem of this type?
P.S.: The device is a Samsung Galaxy S10 (arm64-v8a).

Thanks in advance,

Alex

**Comment by Oleur** [comment]
Thanks for reporting the issue! I'll be checking this week :)

**Comment by alexsaenko27** [comment]
Hi, I managed to solve the problem by re-exporting the unity library.

Regards,

Alex

**Comment by Oleur** [comment]
Awesome I'm glad you fixed it 🙂
